djvenv/mishp/catalog/urls.py
from django.urls import path, include
from . import views

app_name = 'catalog'

urlpatterns = [path('catalog/details/<slug:slug>/', views.details, name='details'),
               path('catalog/<slug:slug>/', views.details_of_category, name='details_of_category'),
               ]

djvenv/mishp/main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'main' # именное пространство

urlpatterns = [path('', views.main_page, name='main_page'),
               path('about/',TemplateView.as_view(template_name='main/about_us.html'), name='about'),
               path('delivery_and_payment/', TemplateView.as_view(template_name='main/delivery.html'), name='delivery_and_payment')
               ]

djvenv/mishp/mishp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('catalog.urls', namespace='catalog')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('api/', include('test_api.urls'))
]
#accounts/login/ [name='login']
#accounts/logout/ [name='logout']
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

djvenv/mishp/main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from catalog.models import Category, InstrumentsCatalog


def main_page(request):# представление списка товаров на странице а так же саппорт ссылки ( 100% рабочее)
    category = Category.objects.all()
    return render(request, 'main/main_page.html', {'category':category})

#def about(request):# представление для О нас --- Работает
#    return render(request, 'main/about_us.html')

djvenv/mishp/templates/main/about_us.html
{% extends 'base.html' %}


{% block title %}<title>О нас</title>{% endblock title %}

{% block content %}
<div id="main" >
    <div class="about_us">



        <h1 class="info_possition">О компании</h1>

        <div class='info_possition_3'>

            <p class="interval">Наш музыкальный магазин создан человеком, для которого музыка – не просто увлечение,
                а стиль жизни. Наша цель – сделать мир музыки ближе и доступнее каждому.
                Мы верим, что любой, кто мечтает заниматься музыкой, должен иметь возможность воплотить свою мечту в реальность.</p>

            <p class="interval">В нашем ассортименте – инструменты и аксессуары для музыкантов любого уровня:
            от начинающих до профессионалов. Мы тщательно подбираем товары, чтобы обеспечить высокое качество по доступным ценам.</p>

            <p class="interval">С музыкой начинается творчество, а с нами – ваш путь в этот удивительный мир.</p>
        </div>

        <div>
            <ul class="about_us_2">
                <li>Адрес: г.Москва ул.//////, дом 2</li>
                <li>Генеральный директор: Чулпанов Владислав Николаевич</li>
                <li>Телефон для связи:8-937-771-55-18</li>
                <li>Email для связи: <a style="color: inherit" href="mailto:vlad.chulpanov@icloud.com">vlad.chulpanov@icloud.com</a></li>
            </ul>
        </div>

    </div>
</div>
{% endblock content %}

djvenv/mishp/templates/main/delivery.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title>Доставка и оплата</title>{% endblock title %}

{% block content %}

<div class="delivery_describe">


        <h1>Информация о доставке и оплате заказов</h1>
    <div class="down">
        <p>Мы автоматически рассчитываем самую выгодную доставку в ваш город исходя из габаритов товара, сроков доставки и тарифов транспортных компаний.</p>
        <p>Укажите свой город в поле ниже и мы покажем все доступные варианты доставки. Точные сроки и окончательную стоимость доставки всего заказа можно</p>
        <p>увидеть в корзине при оформлении заказа.</p>


        <p class="process">Как всё будет происходить?</p>
        <ul class="li_right">
            <li>Вы оформляете заказ на сайте.</li>
            <li>Мы звоним для подтверждения заказа. Без подтверждения заказы не отправляются!</li>
            <li>Согласовываем с вами день и время доставки.</li>
            <li>Дальше собираем заказ, проверяем, упаковываем и передаём в транспортную компанию.</li>
            <li>В назначенный день, в выбранный вами диапазон времени курьер привозит заказ.</li>
        </ul>

        <p style=" margin-top: 5%; font-weight: bold; margin-bottom:6%">Доставка до двери — 2-4 дня</p>
    </div>

</div>

{% endblock content %}
{% comment %} тут надо будет дописать {% endcomment %}

djvenv/mishp/templates/main/main_page.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div id="main">
    <ul>
        {% for i in category %}
        <li class="main-li-poisition"><a href="{% url 'catalog:details_of_category' i.slug %}" class="color-main">{{i.type_of_instruments}}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock content %}