djvenv/mishp/catalog/urls.py
from django.urls import path, include
from . import views

app_name = 'catalog'

urlpatterns = [path('catalog/details/<slug:slug>/', views.details, name='details'),
               path('catalog/<slug:slug>/', views.details_of_category, name='details_of_category'),
               ]

djvenv/mishp/main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'main' # именное пространство

urlpatterns = [path('', views.main_page, name='main_page'),
               path('about/',TemplateView.as_view(template_name='main/about_us.html'), name='about'),
               path('delivery_and_payment/', TemplateView.as_view(template_name='main/delivery.html'), name='delivery_and_payment')
               ]

djvenv/mishp/mishp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('catalog.urls', namespace='catalog')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('api/', include('test_api.urls'))
]
#accounts/login/ [name='login']
#accounts/logout/ [name='logout']
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

djvenv/mishp/catalog/models.py
from django.db import models


class Category(models.Model):

    type_of_instruments = models.CharField(max_length=100)    # тип инструмента
    slug = models.SlugField(null=True)

    class Meta:

        ordering = ['slug']

    def __str__(self):
        return self.type_of_instruments

class ShowcaseOfInstrumentst(models.Model): # Модель с типами товаров электро, бас, акустика, пластик, комбо, голова, кабинет, и т.д.

    goods = models.CharField(max_length=100)
    slug = models.SlugField()
    type_of_instruments_showcase = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.goods


class InstrumentsCatalog(models.Model):

    title = models.CharField(max_length=100)    # фирма производитель
    slug = models.SlugField(unique=True)    # слаг
    model = models.CharField(max_length=100)    # модель инструмента
    availability = models.BooleanField()    # наличие
    quantity = models.IntegerField()    # количство
    price = models.IntegerField()    # цена
    type_of_instruments = models.ForeignKey(Category, on_delete=models.CASCADE, null=True)  # тип инструмента
    type_of_goods = models.ForeignKey(ShowcaseOfInstrumentst, on_delete=models.CASCADE, null=True)

    class Meta:

        ordering = ['slug']

    def __str__(self):
        return self.title

# Добавить индексацию

djvenv/mishp/catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def details_of_category(request, slug):
    '''вернет типы типы инструментов бас,
     электро, акустика и тд'''

    category_of_instr = get_object_or_404(Category, slug=slug) # этим запросом получим категорию инструменов ударные гитары клавиши или прочее, в том числе
    # это будет загловок для шаблона detail_of_category
    value = slug # переменная для того что бы подключались фоны в каталоге

    type_of_instr_in_category = category_of_instr.showcaseofinstrumentst_set.filter(type_of_instruments_showcase_id=category_of_instr) # типы инструментов в категории бас, акустика, электро и тд

    return render(request, 'catalog/details_of_category.html', {'type_of_instr_in_category':type_of_instr_in_category, 'category_of_instr':category_of_instr, 'value':value})


def details(request, slug):
    '''описывает витрину с инструментами в каталоге'''

    goods_in_category_1 = get_object_or_404(ShowcaseOfInstrumentst, slug=slug) # запрос для заголовка шаюлона detail
    goods_in_category = goods_in_category_1.instrumentscatalog_set.all()

    paginator = Paginator(goods_in_category, 5) # постраничная разбивка, пока разбиваем по 5 + добавить обработку исключений
    page_number = request.GET.get('page', 1)
    try:
        instruments_pages = paginator.page(page_number)
    except (EmptyPage, PageNotAnInteger):
        instruments_pages = paginator.page(paginator.num_pages)

    return render(request, 'catalog/detail.html', {'goods_in_category':goods_in_category, 'instruments_pages':instruments_pages, 'goods_in_category_1':goods_in_category_1})

djvenv/mishp/templates/catalog/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<p> <a name="В начало"></a> </p>

<header>
    <h1>{{goods_in_category_1}}</h1>
</header>

{% for i in instruments_pages %}
    <br><br>Фирма производитель: {{i.title}}
    <br><br>Модель:{{i.model}}
    <br><br>Наличие:{{i.availability}}
    <br><br>Количество:{{i.quantity}}
    <br><br>Цена:{{i.price}}

    {% endfor %}



<p>{% include "catalog/details_paginator.html" with page=instruments_pages %}<p/>

<p><a href="#В начало">В начало</a></p>



</body>
</html>

djvenv/mishp/templates/catalog/details_of_category.html
{% extends 'base.html' %}
{% load static %}

{% block title %}<title> Детали категорий </title>{% endblock title %}

{% block link %}

{% if value == 'drums' %}
    <link rel="stylesheet" href="{% static 'css_styles/css_for_catalog_drums.css' %}">

{% elif value == 'keyboards' %}
    <link rel="stylesheet" href="{% static 'css_styles/css_for_catalog_keyboards.css' %}">

{% elif value == 'for-the-studio' %}
    <link rel="stylesheet" href="{% static 'css_styles/css_for_catalog_for_the_studio.css' %}">

{% elif value == 'guitars' %}
    <link rel="stylesheet" href="{% static 'css_styles/css_for_catalog_guitars.css' %}">

{% elif value == 'microphones' %}
    <link rel="stylesheet" href="{% static 'css_styles/css_for_catalog_microphones.css' %}">

{% elif value == 'switching' %}
    <link rel="stylesheet" href="{% static 'css_styles/css_for_catalog_switching.css' %}">

{% elif value == 'guitar-amps' %}
    <link rel="stylesheet" href="{% static 'css_styles/css_for_catalog_guitar_amps.css' %}">
{% endif %}

{% endblock link %}

{% block content %}


    <h1 class="head_of_instruments">{{category_of_instr}}</h1>


<ul class="list_of_instuments">
    {% for i in type_of_instr_in_category %}
    <li >
        <a style="color: white; text-decoration: none" href="{% url 'catalog:details' i.slug %}">{{i.goods}}</a>
    </li>
    {% endfor %}
</ul>
{% endblock content %}

djvenv/mishp/templates/catalog/details_paginator.html
{% if page.has_previous %} <!-- если есть предыдущая страница, то показываем её кнопку -->
   <a href="?page={{ page.previous_page_number }}"> <button> < </button> </a> <!-- возвращает номер предыдущей страницы -->
{% endif %}
   Страница {{ page.number }} из {{ page.paginator.num_pages }}. <!-- текст описание -->
{% if page.has_next %} <!-- если есть следующая страница, то показываем её кнопку -->
<a href="?page={{ page.next_page_number }}"> <button> > </button> <button> Показать еще </button></a> <!-- возвращает номер следующей страницы -->
{% endif %}

djvenv/mishp/templates/catalog/inclusion_tag_category.html
{% for i in all_categories %}
    {{i.type_of_instruments}}
{% endfor %}

djvenv/mishp/templates/catalog/tamplate_for_head_of_category.html
{% for i in all_categories %}
    {{i.type_of_instruments}}
{% endfor %}