djvenv/mishp/main/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'main' # именное пространство

urlpatterns = [path('', views.main_page, name='main_page'),
               path('about/',TemplateView.as_view(template_name='main/about_us.html'), name='about'),
               path('delivery_and_payment/', TemplateView.as_view(template_name='main/delivery.html'), name='delivery_and_payment')
               ]

djvenv/mishp/mishp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('catalog.urls', namespace='catalog')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    path('api/', include('test_api.urls'))
]
#accounts/login/ [name='login']
#accounts/logout/ [name='logout']
#accounts/password_change/ [name='password_change']
#accounts/password_change/done/ [name='password_change_done']
#accounts/password_reset/ [name='password_reset']
#accounts/password_reset/done/ [name='password_reset_done']
#accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
#accounts/reset/done/ [name='password_reset_complete']

djvenv/mishp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}<title>Главная страница</title>{% endblock title %}

    {% block link %}<link rel="stylesheet"  href="{% static 'css_styles/css_for_main_page.css' %}">{% endblock link %}

</head>

<body>


<div id='header' class="position-right">
<ul>
    <li class="header-li-poisition"><a class="settings-h" href="">Корзина</a></li>
    <li class="header-li-poisition"><a class="settings-h" href="">Мои заказы</a></li>
    <li class="header-li-poisition"><a class="settings-h" href="">Избранное</a></li>

    {% if user.is_authenticated %}
        <li class="settings-h header-li-poisition">Привет {{ user.username }}!</li>
        <li class="header-li-poisition">
            <form action="{% url 'logout' %}" method="post" style="display: inline;"> <!--можно применять стили к формам что бы Выход не спусуакадслся вниз применил display: inline-->
                {% csrf_token %}
                <a class="settings-h" href="#" onclick="this.closest('form').submit();">Выход</a>
            </form>
        </li>
    {% else %}
        <li class="header-li-poisition"><a class="settings-h" href="{% url 'login' %}">Вход</a></li>
    {% endif %}
</ul>
</div>

<div>
    {% block content %}

    {% endblock content %}
</div>

<div id="footer">
    <ul>
    <li class="footer-li-poisition"><a class="settings-f" href="{% url 'main:delivery_and_payment' %}">Заказ и оплата</a></li>
    <li class="footer-li-poisition"><a class="settings-f" href =''>Доставка</a></li>
    <li class="footer-li-poisition"><a class="settings-f" href="{% url 'main:about' %}">Наши контакты</a></li>
    </ul>
    <p class="position_right">&copy;2024 My instrument music shop, LLC. All
        rights reserved.</p>
</div>


</body>
</html>